### PR TITLE
feat(firebase_ui_auth): add autofocus property to PhoneInput widget

### PR DESCRIPTION
**Pull request by orenagiv**
## Description

When using the PhoneInput widget as described in the "Using widget" or "Building a custom widget" sections [here](https://github.com/firebase/FirebaseUI-Flutter/blob/main/docs/firebase-ui-auth/providers/phone.md), it usually means there are additional fields or other widgets on screen, and therefore the `autofocus: true` which is currently hard-coded into the PhoneInput widget might conflict with the desired UX of that screen.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
Note: I see errors in `firebase_ui_firestore` (which also exist in the `main` branch), but no issues in the package which this PR relates to (`firebase_ui_auth`).
- [x] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is _not_ a breaking change.

[issue database]: https://github.com/firebase/FirebaseUI-Flutter/issues
[Contributor Guide]: https://github.com/firebase/FirebaseUI-Flutter/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by russellwheatley** [comment]
Hey @orenagiv - thank you for the PR, could you create a small example app demonstrating this use case, please?

**Comment by orenagiv** [comment]
Hey @russellwheatley 
Sure - will send an example ASAP.

**Comment by orenagiv** [comment]
Hey @russellwheatley,
The example app can be found here:
https://github.com/orenagiv/firebase_ui_auth_example

You can use the following phone number and verification code to test the flow:
```
Test phone number: +1 650-555-1234
Verification code: 123456
```

The relevant Widget which demonstrates the usage of the Firebase UI Auth flow is:
```
widgets/sign_in_with_mobile.dart
```

Please let me know if you need anything else.

**Comment by russellwheatley** [comment]
@orenagiv - thank you! I'll take a look at some point this week👌

**Review by russellwheatley — APPROVED** [review]

**Pull request merged**
