### PR TITLE
fix(ui_localizations): In the Japanese file, change "login" to "sign and improve translations

### PR DESCRIPTION
**Pull request by ywake**
## Description

* In the Japanese translation file, "Login" and "Sign in" are mixed, so I unified them with "Sign in" to match the English version.
  * There may be some debate as to whether to use "Login" or "Sign In" for this, but I decided to go with the English version.
* Removed unnatural spaces in Japanese.

> * 日本語翻訳ファイルにおいて、「ログイン」と「サインイン」が混在しているので、英語版に合わせて「サインイン」に統一しました。
>   * 「ログイン」と「サインイン」のどちらを使うべきかには議論があるかもしれませんが、英語版に合わせることにしました。
> * 日本語の不自然な空白を削除しました。

## Related Issues

none

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is _not_ a breaking change.

[issue database]: https://github.com/firebase/FirebaseUI-Flutter/issues
[Contributor Guide]: https://github.com/firebase/FirebaseUI-Flutter/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by russellwheatley** [comment]
Hey @ywake - is it possible you could get another developer fluent in Japanese to review this PR, please? I don't speak Japanese I'm afraid, but I am happy to get this PR merged providing it is an improvement 😄

**Comment by ywake** [comment]
@KoheiKanagu @keigomichi
Hello, friends.
I saw you in a past pull request, so I was wondering if you could review my pull request?

**Review by KoheiKanagu — APPROVED** [review]
LGTM 👍

**Comment by ywake** [comment]
@russellwheatley
I received a review 😄

**Comment by russellwheatley** [comment]
Thanks @KoheiKanagu & @ywake 🙏

**Review by russellwheatley — APPROVED** [review]

**Pull request merged**
