### PR TITLE
feat(ui_localization): Add the translations for the da,nb,sv

### PR DESCRIPTION
**Pull request by asimjawad**
## Description

_Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change._

## Related Issues

_Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/firebase/FirebaseUI-Flutter/issues). Indicate, which of these issues are resolved or fixed by this PR._

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is _not_ a breaking change.

[issue database]: https://github.com/firebase/FirebaseUI-Flutter/issues
[Contributor Guide]: https://github.com/firebase/FirebaseUI-Flutter/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by lesnitsky** [comment]
@asimjawad could you please ask someone else you know who speaks Norsk, Swedish, and Danish to proofread this and approve?

**Comment by asimjawad** [comment]
@lesnitsky I got some people in my company who can do that, let me take the translation files through them and I will get back to you

**Comment by lesnitsky** [comment]
@asimjawad any updates on getting this PR reviewed by someone else who speaks these languages?

**Comment by asimjawad** [comment]
yeah, I asked people in my company who speaks the following languages, they have given me the updated jsons for these, I will be updating the PR soon, can you merge it then?

**Comment by lesnitsky** [comment]
@asimjawad could you please ask those people to approve this PR as well?

**Comment by asimjawad** [comment]
@lesnitsky they are laymen, basically, I do know a guy who speaks polish and a dev, I can ask him to approve it

**Comment by lesnitsky** [comment]
@asimjawad the localization is not for polish though

**Comment by asimjawad** [comment]
@lesnitsky sorry for that, I have been working for 12 hours straight XD

I am out of options then, I can try one of my teammates, who speak these languages, but are not developers.

**Comment by lesnitsky** [comment]
We can't merge it without proofreading, feel free to re-submit if you can find someone who can approve this PR.

**Comment by martinsellergren** [comment]
Swedish looks good (I'm a native speaker).
This update would be great.

**Pull request closed without merging**
