### PR TITLE
fix: update ru translations to remove English duplicates

### PR DESCRIPTION
**Pull request by opimand**
## Description

Elimination of duplicates in the Russian dictionary: removal of repetitive English words has been performed, as they are unnecessary for functionality.
Due to these duplicates, elements of the user interface appear overloaded, often resulting in overflow.
Screenshot 2023-08-21 at 17 34 09

## Related Issues

_Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/firebase/FirebaseUI-Flutter/issues). Indicate, which of these issues are resolved or fixed by this PR._

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is _not_ a breaking change.

[issue database]: https://github.com/firebase/FirebaseUI-Flutter/issues
[Contributor Guide]: https://github.com/firebase/FirebaseUI-Flutter/blob/main/docs/contributing.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by lesnitsky — CHANGES_REQUESTED** [review]
Please update relevant `.arb` file and generate dart class from cli as mention in the [contributing section](https://github.com/firebase/FirebaseUI-Flutter/tree/main/packages/firebase_ui_localizations#contributing) of the docs

**Comment by opimand** [comment]
> Please update relevant `.arb` file and generate dart class from cli as mention in the [contributing section](https://github.com/firebase/FirebaseUI-Flutter/tree/main/packages/firebase_ui_localizations#contributing) of the docs

I tried to run 
`run dart run firebase_ui_localizations:gen_l10n
`
as mentioned in the docs, but got an error every time

```
firebase_ui_localizations % flutter run firebase_ui_localizations:gen_l10n
Target file "firebase_ui_localizations:gen_l10n" not found.
```
May be I missunderstood something? I tried to do that at different directories, all posible I guess  
Thats why I just generete .arb file by Android Studiio

**Review by lesnitsky — APPROVED** [review]

**Comment by opimand** [comment]
> 



> ```shell
> cd packages/firebase_ui_localizations
> dart run firebase_ui_localizations:gen_l10n
> #^^^
> # dart, not flutter
> ```

```
firebase_ui_localizations % dart run firebase_ui_localizations:gen_l10n
Resolving dependencies in /Users/opimand/Documents/dev/FirebaseUI-Flutter/packages/firebase_ui_localizations... 
Because firebase_ui_localizations requires the Flutter SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `dart pub get`.
```

**Review by Lyokone — APPROVED** [review]

**Comment by opimand** [comment]
> art --version

```
 firebase_ui_localizations % dart --version
Dart SDK version: 3.0.7 (stable) (Mon Jul 24 13:17:56 2023 +0000) on "macos_arm64"
```
Works as usual...

**Pull request merged**
